### ISSUE TITLE
Faulty Boards

### ISSUE THREAD

**Issue by GArrigotti-cws** [EnviroDIY/Mayfly-Modbus-Wing#2]
I ordered five of these for a deployment, two of the five appear not to work.

1.  Initially the board appeared to be working, while in sensor testing mode all of the sensors returned valid measurements.  However, I noticed on boot the radio's LTE Bee did not illuminate nor did it illuminate in sensor testing mode.  The radio did not appear to receive any power.

For troubleshooting I originally replaced:

             1.  LTE Bee
             2. Radio (I also connected to XCTU to validate and verify)
             3. Mayfly
             4. Antenna

2.   I went to the second Modbus Wing when none of the above worked.  When I plugged in the second Modbus Wing and provided power it immediately caused the Mayfly to catch fire.  So I validated the jumper cable, I did not check the power regulator but either way it shorted.

The other ones worked fantastic, wanted to annotate the above experience for tracking.

**Comment by neilh10** [comment]
Gosh, yes there can be problems with boards. This should be addressed directly with who you ordered them from. 

For open source hardware, there is the ability to look into the design, read the schematics and compare it to the board.  
In the early stages of a manufacturing run this can be valuable to be able to look at what might have caused any problems - is it manufacturing issue or a design issue. This can make it easier for specialist equipment to be more finely tuned. 

I think I should add a test section for this board.

Personally, for any boards that I test and supply I would give them a serial number to be tracked by, so that they can be referenced if something isn't operational. 

Hardware Modbus/RS485 testing would verify the separate hardware elements 1) that it works with any (simple) RS485 instrument as determined by the software, 2) the LEDs flash orange (red/green) with an instrument attached  3) flash red with no instrument attached  4) SDI-12 testing would verify basic (simple) equipment response as verified by software.

**Comment by neilh10** [comment]
I added a test section for the hardware. 
Its concerning when something has problems, however I would see this section address design issues, and for that each hardware unit needs to be tested after manufacturing to see that it works. 
When working, and under normal conditions such as a shorted line, it should not fail.
I would see this section only tracks the hardware.  The larger part of how it fits into software would be addressed in the software package
GArrigotti-cws if you see different please re-open with follow up information.

**Comment by aufdenkampe** [comment]
@neilh10, thanks for responding to this issue. As you know, I supplied the boards to @GArrigotti-cws after soldering on the Pololu step-up voltage boosters and screw terminals.

I have 3 of the faulty boards back in hand and am beginning testing to see what might have happened to them. I just studied the [knh002r7 schematicRs485.pdf](https://github.com/EnviroDIY/Mayfly-Modbus-Wing/blob/master/knh002-MayflyWingShield/rev7/knh002r7%20schematicRs485.pdf ) and the [KNH002 Circuit Discription](https://github.com/EnviroDIY/Mayfly-Modbus-Wing/tree/master/knh002-MayflyWingShield#knh002-circuit-discription) and have a couple of questions about power delivery capabilities. For background, my understanding is that all boards that failed were loaded with 3-5 Modbus sensors, with at least 1 having a brushing motor.

I see that the power supply to all the sensors is limited by a 155mA fuse at R8 that is "guaranteed trip at 350mA". Also, I'm assuming that once this fuse trips, it would need to be replaced. Is that right?

I'm presently thinking that this might be the issue during spikes in power demand, especially when the brushes are activated. We know from early testing of the YosemiTech Y511 turbidity sensor at 9V that there is a ~290mA spike for 10-15 milliseconds, followed by an exponential decay. See https://github.com/EnviroDIY/YosemitechModbus#power-supply
With additional sensors attached, it is very likely that a power spikes could have exceeded the 350mA trip limit.
  
The previous, much simpler board, didn't have such a fuse, so I suppose power handling on those Modbus Wings was limited by the [Pololu 12V Step-Up Voltage Regulator U3V12F12](https://www.pololu.com/product/2117), which had an upper output current of ~430mA for the 12V regulator (powered by the 5V Mayfly switched power rail) or ~600mA for the 9V regulator. See the power curves in the specs. My understanding is that the 500mA limit on the Mayfly power supply isn't a limiting factor for brief power spikes, because of the large capacitors on the input voltage to the regulator. Am I thinking of this correctly?

I have yet to wire up these "faulty" boards for testing, but if the R8 fuse proves to be an issue, is it a viable quick fix to use a blob of solder to jump over and bypass the fuse?

Last, as you know, the [Pololu 12V Step-Up Voltage Regulator U3V12F12](https://www.pololu.com/product/2117) has been discontinued. Any recommendations on a replacement?

Thanks in advance for your insight!

**Comment by neilh10** [comment]
Quick answer - 
electronic fuses are automatically resettable (i've updated description). Bypass e-fuse at the risk of bricking the board.
eFuses are thermal devices, so its 350mA for  some 1sec (I think) - seems unlikely to blow board.
Previously Mayfly 3.3V regulators limited power deliver to 1.65W

What was the failure symptom.? If not a hard failure (smoking) can it be duplicated.
I have found if for the standard 4400mAh battery if below 3.8V and there is a longer battery power wire (with a switch on it) the effective battery impedance increases and it can cause a processor reset.
